version: '3'

services:
  #flyway:
    #image: boxfuse/flyway:5.2.4
    #command: -url=jdbc:mysql://db -schemas=dev_alert -user=root -password=unix11 -connectRetries=60 migrate
    #volumes:
      #- ./src/main/resources/migration/local:/flyway/sql
    #depends_on:
      #- db
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=dev_alert
      - MYSQL_USER=gsimkin01
      - MYSQL_PASSWORD=6001@6001
      - MYSQL_ROOT_PASSWORD=unix11
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3309:3306

